### ISSUE TITLE
needs update for patch 80

### ISSUE THREAD

**Issue by Owyn** [Tera-Shiraneko/cross-server-tooltip#1]
yes

**Comment by Tera-Shiraneko** [comment]
Sry for late reply will update it as soon as possible.

**Comment by Tera-Shiraneko** [comment]
I will be able to update it after Caali is updating S_USER_PAPERDOLL_INFO don't know when he will push it.

**Comment by Tera-Shiraneko** [comment]
The module has been updated now and everything is working again. (Additionally added new relic passivities).
